language: c

sudo: required

services:
  - docker

matrix:
    include:
        - os: linux
          env: TARGET_ENVIRONMENT=ubuntu-xenial-gcc
        - os: linux
          env: TARGET_ENVIRONMENT=ubuntu-xenial-clang
        - os: linux
          env: TARGET_ENVIRONMENT=ubuntu-artful-gcc
        - os: linux
          env: TARGET_ENVIRONMENT=ubuntu-artful-clang
        - os: osx
          env: TARGET_ENVIRONMENT=osx-macports

script:
  - if [[ "$TARGET_ENVIRONMENT" == "ubuntu-xenial-gcc"   ]]; then docker build --rm -t ${TARGET_ENVIRONMENT} -f misc/docker/Dockerfile-${TARGET_ENVIRONMENT} . ; fi
  - if [[ "$TARGET_ENVIRONMENT" == "ubuntu-xenial-clang" ]]; then docker build --rm -t ${TARGET_ENVIRONMENT} -f misc/docker/Dockerfile-${TARGET_ENVIRONMENT} . ; fi
  - if [[ "$TARGET_ENVIRONMENT" == "ubuntu-artful-gcc"   ]]; then docker build --rm -t ${TARGET_ENVIRONMENT} -f misc/docker/Dockerfile-${TARGET_ENVIRONMENT} . ; fi
  - if [[ "$TARGET_ENVIRONMENT" == "ubuntu-artful-clang" ]]; then docker build --rm -t ${TARGET_ENVIRONMENT} -f misc/docker/Dockerfile-${TARGET_ENVIRONMENT} . ; fi
  - if [[ "$TARGET_ENVIRONMENT" == "osx-macports"        ]]; then ./.travis-osx-macports.sh ; fi
